### ISSUE TITLE
Allow to encode list of maps without newlines

### ISSUE THREAD

**Issue by alexeyinkin** [gmpassos/yaml_writer#4]
This code:
```dart
import 'package:yaml_writer/yaml_writer.dart';

void main() {
  const input = [{'a': 1, 'b': 2}, {'c': 3, 'd': 4}];
  final writer = YAMLWriter();
  print(writer.write(input));
}
```

produces output:
```yaml
- 
  a: 1
  b: 2
- 
  c: 3
  d: 4
```

Would be nice to have an option to produce this:
```yaml
- a: 1
  b: 2
- c: 3
  d: 4
```
This is the default formatting of IntelliJ.
